# Generated by Django 2.2.3 on 2020-10-28 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201027_2300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
