# Generated by Django 2.2.3 on 2020-11-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_delete_blogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
