# Generated by Django 2.2.3 on 2020-11-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_linkedvideos_post_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='localvideos',
            name='post_label',
            field=models.CharField(blank=True, choices=[('er_hist', 'Eritrean Histories'), ('er_cult', 'Eritrean Culture'), ('er_polt', 'Politics'), ('er_peop', 'People')], max_length=200, null=True),
        ),
    ]
