# Generated by Django 3.1.1 on 2020-12-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_localvideos_post_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedvideos',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='linkedvideos',
            name='post_label',
            field=models.CharField(blank=True, choices=[('er_hist', 'Eritrean Histories'), ('er_cult', 'Eritrean Culture'), ('er_polt', 'Politics'), ('er_peop', 'People'), ('er_tech', 'Technology'), ('other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='localvideos',
            name='post_label',
            field=models.CharField(blank=True, choices=[('er_hist', 'Eritrean Histories'), ('er_cult', 'Eritrean Culture'), ('er_polt', 'Politics'), ('er_peop', 'People'), ('er_tech', 'Technology'), ('other', 'Other')], max_length=200, null=True),
        ),
    ]
