# Generated by Django 2.2.3 on 2020-10-20 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publisher',
            new_name='LinkedVideoPublisher',
        ),
    ]
