# Generated by Django 2.2.3 on 2020-10-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20201020_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedvideopublisher',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
