# Generated by Django 2.2.3 on 2020-10-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20201020_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedvideopublisher',
            name='dispaly_row',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='linkedvideopublisher',
            name='image',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
