# Generated by Django 2.2.3 on 2020-10-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20201020_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedvideopublisher',
            name='dispaly_row',
            field=models.PositiveIntegerField(default=2, max_length=1),
        ),
    ]
