# Generated by Django 2.2.3 on 2020-10-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20201020_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkedvideopublisher',
            old_name='dispaly_row',
            new_name='display_row',
        ),
    ]
