# Generated by Django 2.2.3 on 2020-10-24 17:29

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20201020_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedvideopublisher',
            name='link',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
