# Generated by Django 2.2.3 on 2020-10-25 14:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0007_auto_20201024_1829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinkedVideoPublisher',
            new_name='HomeView',
        ),
    ]
