# Generated by Django 2.2.3 on 2020-10-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20201025_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='text',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='link',
        ),
        migrations.RemoveField(
            model_name='localvideos',
            name='link',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='link',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='image',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='link',
        ),
        migrations.RemoveField(
            model_name='trending',
            name='text',
        ),
        migrations.AddField(
            model_name='localvideos',
            name='local_video_file',
            field=models.FileField(default='', upload_to='local_videos'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='link',
            field=models.URLField(),
        ),
    ]
