# Generated by Django 2.2.3 on 2020-10-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20201025_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='linkedvideos',
            name='author',
        ),
        migrations.RemoveField(
            model_name='localvideos',
            name='author',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='author',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='LinkedVideos',
        ),
        migrations.DeleteModel(
            name='LocalVideos',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
