# Generated by Django 2.2.3 on 2020-10-30 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_delete_blogs'),
        ('management', '0013_auto_20201030_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='trend_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.LinkedVideos'),
        ),
    ]
