# Generated by Django 2.2.3 on 2020-10-30 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_trending_trend_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='trend_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='posts.LinkedVideos'),
        ),
    ]
