# Generated by Django 2.2.3 on 2020-10-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_homebasetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebasetext',
            name='text',
            field=models.CharField(max_length=5000),
        ),
    ]
