# Generated by Django 2.2.3 on 2020-10-30 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20201030_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebasetext',
            name='text',
            field=models.TextField(),
        ),
    ]
