# Generated by Django 2.2.3 on 2020-11-03 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_auto_20201030_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('top_cover_image', models.ImageField(default='img/blogs/23_Zapab4A.jpg', upload_to='post_page_top_cover')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
