# Generated by Django 2.2.3 on 2020-11-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_postspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postspage',
            name='top_cover_image',
            field=models.ImageField(upload_to='post_page_top_cover'),
        ),
    ]
