# Generated by Django 2.2.3 on 2020-11-03 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20201103_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='postspage',
            name='blog_article_tag_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post_page_top_cover'),
        ),
        migrations.AddField(
            model_name='postspage',
            name='blog_article_tag_text',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postspage',
            name='blog_article_tag_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
        ),
        migrations.AddField(
            model_name='postspage',
            name='video_tag_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='post_page_top_cover'),
        ),
        migrations.AddField(
            model_name='postspage',
            name='video_tag_text',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postspage',
            name='video_tag_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
        ),
        migrations.AlterField(
            model_name='postspage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
