# Generated by Django 2.2.3 on 2020-11-03 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_auto_20201103_0151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostsPage',
        ),
    ]
