# Generated by Django 2.2.3 on 2020-11-03 01:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_delete_postspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('top_cover_image', models.ImageField(upload_to='post_page_top_cover')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('video_tag_image', models.ImageField(upload_to='post_page_top_cover')),
                ('video_tag_title', models.CharField(max_length=200)),
                ('video_tag_text', models.TextField()),
                ('blog_article_tag_image', models.ImageField(upload_to='post_page_top_cover')),
                ('blog_article_tag_title', models.CharField(max_length=200)),
                ('blog_article_tag_text', models.TextField()),
            ],
        ),
    ]
