# Generated by Django 2.2.3 on 2020-11-07 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_postspage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ads',
        ),
    ]
