# Generated by Django 2.2.3 on 2020-11-07 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0025_delete_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='post_page_top_cover')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('about_video', models.FileField(default='', upload_to='about')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
