# Generated by Django 2.2.3 on 2020-11-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_aboutvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutvideo',
            old_name='about_video',
            new_name='local_video_file',
        ),
    ]
