# Generated by Django 2.2.3 on 2020-11-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_auto_20201107_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_email', models.EmailField(max_length=255)),
                ('check', models.BooleanField(default=True)),
            ],
        ),
    ]
