# Generated by Django 2.2.3 on 2020-11-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_emailsubscriptions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsubscriptions',
            old_name='check',
            new_name='is_subscriber_active',
        ),
    ]
