# Generated by Django 2.2.3 on 2020-11-18 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_feedbacksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsubscriptions',
            name='subscribed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='feedbacksubmission',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
