# Generated by Django 2.2.3 on 2020-11-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_auto_20201118_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('to', models.EmailField(max_length=255)),
                ('e_from', models.CharField(max_length=255)),
                ('subject', models.TextField()),
                ('sent', models.BooleanField(default=False)),
                ('sent_on', models.DateTimeField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('newsletter_notifier', 'Newsletter Subscribers Notifier'), ('individual_email', 'Individual'), ('other', 'Other')], max_length=200, null=True)),
            ],
        ),
    ]
