# Generated by Django 2.2.3 on 2020-11-18 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_auto_20201119_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsender',
            name='sent',
        ),
        migrations.AlterField(
            model_name='emailsender',
            name='e_from',
            field=models.EmailField(default='negusebf12@gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailsender',
            name='message',
            field=models.TextField(default='This is an important message.'),
        ),
        migrations.AlterField(
            model_name='emailsender',
            name='subject',
            field=models.CharField(default='Negusse Test Website (AUTOMATIC EMAIL SENDER)', max_length=255),
        ),
    ]
