# Generated by Django 2.2.3 on 2020-11-19 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_auto_20201119_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAdsManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=255)),
                ('ad', models.ImageField(upload_to='img/manual_ads')),
                ('ad_link', models.URLField()),
                ('ad_category', models.CharField(choices=[('side', 'Side (Must be 360 by 370)'), ('bottom', 'Bottom (Must be 1260 by 370)')], max_length=255)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
