# Generated by Django 2.2.3 on 2020-10-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20201029_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_cover_image',
            field=models.ImageField(blank=True, upload_to='img/blogs'),
        ),
    ]
