# Generated by Django 2.2.3 on 2020-10-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20201030_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_cover_image',
            field=models.ImageField(blank=True, default=None, upload_to='img/blogs'),
        ),
    ]
