# Generated by Django 2.2.3 on 2020-10-30 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20201030_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_cover_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img/blogs'),
        ),
    ]
