# Generated by Django 2.2.3 on 2020-10-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_auto_20201030_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_cover_image',
            field=models.ImageField(default='img/blogs/23_Zapab4A.jpg', upload_to='img/blogs'),
        ),
    ]
