# Generated by Django 2.2.3 on 2020-11-03 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_auto_20201030_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_cover_image',
            field=models.ImageField(default='img/blogs/23', upload_to='img/blogs'),
        ),
    ]
