# Generated by Django 2.2.3 on 2020-11-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20201103_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_labe',
            field=models.CharField(blank=True, choices=[('er_hist', 'Eritrean Histories'), ('er_cult', 'Eritrean Culture'), ('er_polt', 'Politics'), ('er_peop', 'Politics')], max_length=200, null=True),
        ),
    ]
