# Generated by Django 2.2.3 on 2020-11-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0018_auto_20201103_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_label',
            field=models.CharField(blank=True, choices=[('er_hist', 'Eritrean Histories'), ('er_cult', 'Eritrean Culture'), ('er_polt', 'Politics'), ('er_peop', 'People')], max_length=200, null=True),
        ),
    ]
