# Generated by Django 2.2.3 on 2020-11-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_auto_20201103_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_cover_image',
            field=models.ImageField(default='img/blogs/23', upload_to='img/blogs/'),
        ),
    ]
