# Generated by Django 2.2.3 on 2020-11-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_auto_20201121_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_cover_image',
            field=models.ImageField(upload_to='img/blogs/'),
        ),
    ]
